In [2]:
import pandas as pd 
import numpy as np

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [7]:
file_url='https://raw.githubusercontent.com/PacktWorkshops/The-Data-Science-Workshop/master/Chapter03/bank-full.csv'
bankData=pd.read_csv(file_url,sep=';')
bankData.head(10)

age           job   marital  education default  balance housing loan  \
0   58    management   married   tertiary      no     2143     yes   no   
1   44    technician    single  secondary      no       29     yes   no   
2   33  entrepreneur   married  secondary      no        2     yes  yes   
3   47   blue-collar   married    unknown      no     1506     yes   no   
4   33       unknown    single    unknown      no        1      no   no   
5   35    management   married   tertiary      no      231     yes   no   
6   28    management    single   tertiary      no      447     yes  yes   
7   42  entrepreneur  divorced   tertiary     yes        2     yes   no   
8   58       retired   married    primary      no      121     yes   no   
9   43    technician    single  secondary      no      593     yes   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no  
5  unknown    5   may       139         1     -1         0  unknown  no  
6  unknown    5   may       217         1     -1         0  unknown  no  
7  unknown    5   may       380         1     -1         0  unknown  no  
8  unknown    5   may        50         1     -1         0  unknown  no  
9  unknown    5   may        55         1     -1         0  unknown  no

In [9]:
bankData.dtypes

age           int64
job          object
marital      object
education    object
default      object
balance       int64
housing      object
loan         object
contact      object
day           int64
month        object
duration      int64
campaign      int64
pdays         int64
previous      int64
poutcome     object
y            object
dtype: object

In [10]:
bankData.shape

(45211, 17)

In [39]:
bankCat=pd.get_dummies(bankData[['job','marital','education','default','housing'
         ,'loan','contact','month','poutcome']])



In [40]:
bankNum=bankData[['age','balance','day','duration','campaign','pdays'
                 ,'previous']]

In [16]:
len(bankCat)

45211

In [46]:
X=pd.concat([bankCat,bankNum],axis=1)
X.shape

(45211, 51)

In [47]:
Y=bankData['y']


In [48]:
train_x,test_x,train_y,test_y=train_test_split(X,Y,test_size=0.33,random_state=123)

In [35]:
len(train_x)

30291

In [22]:
len(test)

14920

In [49]:
train_y

42653     no
1895      no
25451     no
21142     no
24513     no
        ... 
7763     yes
15377     no
17730     no
28030     no
15725     no
Name: y, Length: 30291, dtype: object

In [51]:
bankModel=LogisticRegression()
bankModel.fit(train_x,train_y)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [58]:
pred=bankModel.predict(test_x)

In [53]:
pred

array(['no', 'no', 'no', ..., 'no', 'no', 'no'], dtype=object)

In [55]:
print('Accuracy of Logistic regression model prediction on test set: {:.2f}'.format(bankModel.score(test_x, test_y)))

Accuracy of Logistic regression model prediction on test set: 0.89


In [59]:
from sklearn.metrics import confusion_matrix
confusionmatrix=confusion_matrix(test_y,pred)
confusionmatrix

array([[12914,   264],
       [ 1359,   383]])

In [61]:
 from sklearn.metrics import f1_score

In [70]:
f1_score(test_y,pred,average=None,labels=['yes','no'])

array([0.32063625, 0.94087647])

In [1]:
import pandas as pd
import numpy as np

In [8]:
filename="https://raw.githubusercontent.com/PacktWorkshops/The-Data-Science-Workshop/master/Chapter03/bank-full.csv"
bankData=pd.read_csv(filename,sep=";")


In [9]:
bankData.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

In [10]:
from sklearn import preprocessing

In [21]:
x=bankData[['balance']].values.astype(float)

In [22]:
x

array([[2.143e+03],
       [2.900e+01],
       [2.000e+00],
       ...,
       [5.715e+03],
       [6.680e+02],
       [2.971e+03]])

In [16]:
minmaxScaler=preprocessing.MinMaxScaler()

In [32]:
bankData['balanceTran']=minmaxScaler.fit_transform(x)

In [33]:
bankData['balanceTran']=bankData['balanceTran']+0.00001

In [34]:
bankData.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  \
0  unknown    5   may       261         1     -1         0  unknown  no   
1  unknown    5   may       151         1     -1         0  unknown  no   
2  unknown    5   may        76         1     -1         0  unknown  no   
3  unknown    5   may        92         1     -1         0  unknown  no   
4  unknown    5   may       198         1     -1         0  unknown  no   

   balanceTran  
0     0.092269  
1     0.073077  
2     0.072832  
3     0.086486  
4     0.072822

In [35]:
bankData['loanTran']=1

In [36]:
bankData.loc[bankData['loan']=='no','loanTran']=5


In [37]:
bankData.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  \
0  unknown    5   may       261         1     -1         0  unknown  no   
1  unknown    5   may       151         1     -1         0  unknown  no   
2  unknown    5   may        76         1     -1         0  unknown  no   
3  unknown    5   may        92         1     -1         0  unknown  no   
4  unknown    5   may       198         1     -1         0  unknown  no   

   balanceTran  loanTran  
0     0.092269         5  
1     0.073077         5  
2     0.072832         1  
3     0.086486         5  
4     0.072822         5

In [38]:
bankData['houseTran']=5

In [40]:
bankData.loc[bankData['housing']=="no","houseTran"]=1

In [41]:
bankData.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  \
0  unknown    5   may       261         1     -1         0  unknown  no   
1  unknown    5   may       151         1     -1         0  unknown  no   
2  unknown    5   may        76         1     -1         0  unknown  no   
3  unknown    5   may        92         1     -1         0  unknown  no   
4  unknown    5   may       198         1     -1         0  unknown  no   

   balanceTran  loanTran  houseTran  
0     0.092269         5          5  
1     0.073077         5          5  
2     0.072832         1          5  
3     0.086486         5          5  
4     0.072822         5          1

In [50]:
bankData['assetIndex']=bankData['balanceTran']*bankData['loanTran']*bankData['houseTran']


In [53]:
bankData.tail(20)

age            job   marital  education default  balance housing loan  \
45191   75        retired  divorced   tertiary      no     3810     yes   no   
45192   29     management    single   tertiary      no      765      no   no   
45193   28  self-employed    single   tertiary      no      159      no   no   
45194   59     management   married   tertiary      no      138     yes  yes   
45195   68        retired   married  secondary      no     1146      no   no   
45196   25        student    single  secondary      no      358      no   no   
45197   36     management    single  secondary      no     1511     yes   no   
45198   37     management   married   tertiary      no     1428      no   no   
45199   34    blue-collar    single  secondary      no     1475     yes   no   
45200   38     technician   married  secondary      no      557     yes   no   
45201   53     management   married   tertiary      no      583      no   no   
45202   34         admin.    single  secondary      no      557      no   no   
45203   23        student    single   tertiary      no      113      no   no   
45204   73        retired   married  secondary      no     2850      no   no   
45205   25     technician    single  secondary      no      505      no  yes   
45206   51     technician   married   tertiary      no      825      no   no   
45207   71        retired  divorced    primary      no     1729      no   no   
45208   72        retired   married  secondary      no     5715      no   no   
45209   57    blue-collar   married  secondary      no      668      no   no   
45210   37   entrepreneur   married  secondary      no     2971      no   no   

         contact  day  ... campaign  pdays  previous  poutcome    y  \
45191   cellular   16  ...        1    183         1   failure  yes   
45192   cellular   16  ...        1     -1         0   unknown  yes   
45193   cellular   16  ...        2     33         4   success  yes   
45194   cellular   16  ...        2    187         5   failure   no   
45195   cellular   16  ...        1    187         6   success  yes   
45196   cellular   16  ...        1     -1         0   unknown  yes   
45197   cellular   16  ...        1     -1         0   unknown  yes   
45198   cellular   16  ...        2     -1         0   unknown   no   
45199   cellular   16  ...        3    530        12     other   no   
45200   cellular   16  ...        4     -1         0   unknown  yes   
45201   cellular   17  ...        1    184         4   success  yes   
45202   cellular   17  ...        1     -1         0   unknown  yes   
45203   cellular   17  ...        1     -1         0   unknown  yes   
45204   cellular   17  ...        1     40         8   failure  yes   
45205   cellular   17  ...        2     -1         0   unknown  yes   
45206   cellular   17  ...        3     -1         0   unknown  yes   
45207   cellular   17  ...        2     -1         0   unknown  yes   
45208   cellular   17  ...        5    184         3   success  yes   
45209  telephone   17  ...        4     -1         0   unknown   no   
45210   cellular   17  ...        2    188        11     other   no   

      balanceTran loanTran  houseTran  assetIndecx  assetIndex  
45191    0.107404        5          5     2.685096    2.685096  
45192    0.079759        5          1     0.398793    0.398793  
45193    0.074257        5          1     0.371285    0.371285  
45194    0.074066        1          5     0.370331    0.370331  
45195    0.083218        5          1     0.416089    0.416089  
45196    0.076064        5          1     0.380318    0.380318  
45197    0.086532        5          5     2.163288    2.163288  
45198    0.085778        5          1     0.428890    0.428890  
45199    0.086205        5          5     2.155117    2.155117  
45200    0.077870        5          5     1.946757    1.946757  
45201    0.078106        5          1     0.390532    0.390532  
45202    0.077870        5          1     0.389351    

In [54]:
np.quantile(bankData['assetIndex'],[0.25,0.5,0.75])

array([0.37668646, 0.56920367, 1.9027249 ])

In [55]:
bankData['assetClass']='Quant1'

In [56]:
bankData.loc[(bankData['assetIndex']>0.38) &(bankData['assetIndex']<0.57),'assetClass']='Quant2'

In [57]:
bankData.loc[(bankData['assetIndex']>0.57) &(bankData['assetIndex']<1.9),'assetClass']='Quant3'

In [58]:
bankData.loc[bankData['assetIndex']>1.9,"assetClass"]="Quant4"

In [66]:
bankData.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day  ... pdays  previous  poutcome   y  balanceTran loanTran  \
0  unknown    5  ...    -1         0   unknown  no     0.092269        5   
1  unknown    5  ...    -1         0   unknown  no     0.073077        5   
2  unknown    5  ...    -1         0   unknown  no     0.072832        1   
3  unknown    5  ...    -1         0   unknown  no     0.086486        5   
4  unknown    5  ...    -1         0   unknown  no     0.072822        5   

  houseTran  assetIndecx  assetIndex  assetClass  
0         5     2.306734    2.306734      Quant4  
1         5     1.826916    1.826916      Quant3  
2         5     0.364158    0.364158      Quant1  
3         5     2.162153    2.162153      Quant4  
4         1     0.364112    0.364112      Quant1  

[5 rows x 23 columns]

In [67]:
assetTot=bankData.groupby('assetClass')['y'].agg(assetTot
                                                 ='count').reset_index()

In [73]:
assetTot

assetClass  assetTot
0     Quant1     12212
1     Quant2     10400
2     Quant3     11121
3     Quant4     11478

In [74]:
assetProp=bankData.groupby(['assetClass','y'])['y'].agg(
assetCat='count').reset_index()

assetProp

assetClass    y  assetCat
0     Quant1   no     10921
1     Quant1  yes      1291
2     Quant2   no      8436
3     Quant2  yes      1964
4     Quant3   no     10144
5     Quant3  yes       977
6     Quant4   no     10421
7     Quant4  yes      1057

In [75]:
assetComb=pd.merge(assetProp,assetTot,on=['assetClass'])

In [76]:
assetComb

assetClass    y  assetCat  assetTot
0     Quant1   no     10921     12212
1     Quant1  yes      1291     12212
2     Quant2   no      8436     10400
3     Quant2  yes      1964     10400
4     Quant3   no     10144     11121
5     Quant3  yes       977     11121
6     Quant4   no     10421     11478
7     Quant4  yes      1057     11478

In [77]:
assetComb['catProp']=(assetComb.assetCat/assetComb.assetTot)*100

In [78]:
assetComb

assetClass    y  assetCat  assetTot    catProp
0     Quant1   no     10921     12212  89.428431
1     Quant1  yes      1291     12212  10.571569
2     Quant2   no      8436     10400  81.115385
3     Quant2  yes      1964     10400  18.884615
4     Quant3   no     10144     11121  91.214819
5     Quant3  yes       977     11121   8.785181
6     Quant4   no     10421     11478  90.791079
7     Quant4  yes      1057     11478   9.208921

In [79]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [80]:
bankData.dtypes

age              int64
job             object
marital         object
education       object
default         object
balance          int64
housing         object
loan            object
contact         object
day              int64
month           object
duration         int64
campaign         int64
pdays            int64
previous         int64
poutcome        object
y               object
balanceTran    float64
loanTran         int64
houseTran        int64
assetIndecx    float64
assetIndex     float64
assetClass      object
dtype: object

In [3]:
filename="https://raw.githubusercontent.com/PacktWorkshops/The-Data-Science-Workshop/master/Chapter03/bank-full.csv"
BankData=pd.read_csv(filename,sep=";")

In [4]:
BankData.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

In [83]:
BankData.dtypes


age           int64
job          object
marital      object
education    object
default      object
balance       int64
housing      object
loan         object
contact      object
day           int64
month        object
duration      int64
campaign      int64
pdays         int64
previous      int64
poutcome     object
y            object
dtype: object

In [5]:
bankCat=pd.get_dummies(BankData[['job','marital','education',
                                'default','housing','loan'
                                ,'contact','month','poutcome']])

In [6]:
bankCat.shape

(45211, 44)

In [7]:
bankNum=BankData[['age','balance','day','duration','campaign',
                  'pdays','previous']]

In [8]:
bankNum.shape

(45211, 7)

In [9]:
X=pd.concat([bankCat,bankNum],axis=1)

In [11]:
Y=BankData['y']

In [12]:
X.head()

job_admin.  job_blue-collar  job_entrepreneur  job_housemaid  \
0           0                0                 0              0   
1           0                0                 0              0   
2           0                0                 1              0   
3           0                1                 0              0   
4           0                0                 0              0   

   job_management  job_retired  job_self-employed  job_services  job_student  \
0               1            0                  0             0            0   
1               0            0                  0             0            0   
2               0            0                  0             0            0   
3               0            0                  0             0            0   
4               0            0                  0             0            0   

   job_technician  ...  poutcome_other  poutcome_success  poutcome_unknown  \
0               0  ...               0                 0                 1   
1               1  ...               0                 0                 1   
2               0  ...               0                 0                 1   
3               0  ...               0                 0                 1   
4               0  ...               0                 0                 1   

   age  balance  day  duration  campaign  pdays  previous  
0   58     2143    5       261         1     -1         0  
1   44       29    5       151         1     -1         0  
2   33        2    5        76         1     -1         0  
3   47     1506    5        92         1     -1         0  
4   33        1    5       198         1     -1         0  

[5 rows x 51 columns]

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

train_x,test_x,train_y,test_y=train_test_split(X,Y,test_size=0.3
                                             , random_state=123)

In [17]:
bankModel=LogisticRegression()
bankModel.fit(train_x,train_y)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [18]:
pred=bankModel.predict(test_x)

In [19]:
pred

array(['no', 'no', 'no', ..., 'no', 'no', 'no'], dtype=object)

In [20]:
 from sklearn.metrics import f1_score

In [22]:
f1_score(test_y,pred,average=None,labels=['yes','no'])

array([0.30365511, 0.94054573])

In [23]:
bankData.dtypes

NameError: name 'bankData' is not defined

In [24]:
from sklearn import preprocessing

In [25]:
BankData.dtypes

age           int64
job          object
marital      object
education    object
default      object
balance       int64
housing      object
loan         object
contact      object
day           int64
month        object
duration      int64
campaign      int64
pdays         int64
previous      int64
poutcome     object
y            object
dtype: object

In [26]:
BankData['loanTran']=1
BankData.loc[BankData['loan']=='no',"loanTran"]=5

In [27]:
BankData.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  \
0  unknown    5   may       261         1     -1         0  unknown  no   
1  unknown    5   may       151         1     -1         0  unknown  no   
2  unknown    5   may        76         1     -1         0  unknown  no   
3  unknown    5   may        92         1     -1         0  unknown  no   
4  unknown    5   may       198         1     -1         0  unknown  no   

   loanTran  
0         5  
1         5  
2         1  
3         5  
4         5

In [28]:
BankData['houseTran']=1
BankData.loc[BankData['housing']=='yes','houseTran']=5

In [32]:
minmaxScaler=preprocessing.MinMaxScaler()
x=BankData[['balance']].values.astype(float)
BankData['balanceTran']=minmaxScaler.fit_transform(x)
BankData['balanceTran']=BankData['balanceTran']+0.00001
BankData.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  \
0  unknown    5   may       261         1     -1         0  unknown  no   
1  unknown    5   may       151         1     -1         0  unknown  no   
2  unknown    5   may        76         1     -1         0  unknown  no   
3  unknown    5   may        92         1     -1         0  unknown  no   
4  unknown    5   may       198         1     -1         0  unknown  no   

   loanTran  houseTran  balanceTran  
0         5          5     0.092269  
1         5          5     0.073077  
2         1          5     0.072832  
3         5          5     0.086486  
4         5          1     0.072822

In [33]:
BankData['assetIndex']=BankData['loanTran']*BankData['houseTran']*BankData['balanceTran']

In [35]:
BankData.dtypes

age              int64
job             object
marital         object
education       object
default         object
balance          int64
housing         object
loan            object
contact         object
day              int64
month           object
duration         int64
campaign         int64
pdays            int64
previous         int64
poutcome        object
y               object
loanTran         int64
houseTran        int64
balanceTran    float64
assetIndex     float64
dtype: object

In [36]:
BankCat=pd.get_dummies(BankData[['job','marital','education','default','contact','month','poutcome']])

In [38]:
BankCat.shape

(45211, 40)

In [39]:
BankNum=BankData[['age','day','duration','campaign','pdays','previous','assetIndex']]

In [41]:
BankNum.head()

age  day  duration  campaign  pdays  previous  assetIndex
0   58    5       261         1     -1         0    2.306734
1   44    5       151         1     -1         0    1.826916
2   33    5        76         1     -1         0    0.364158
3   47    5        92         1     -1         0    2.162153
4   33    5       198         1     -1         0    0.364112

In [42]:
ageT=BankNum[['age']].values.astype(float)
dayT=BankNum[['day']].values.astype(float)
durationT=bankNum[['duration']].values.astype(float)

In [49]:
BankNum['ageTran']=minmaxScaler.fit_transform(ageT)

<ipython-input-49-73480abeb0eb>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  BankNum['ageTran']=minmaxScaler.fit_transform(ageT)


In [44]:
BankNum['dayTran']=minmaxScaler.fit_transform(dayT)
BankNum['durationTran']=minmaxScaler.fit_transform(durationT)

<ipython-input-44-368e1a69aea5>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  BankNum['dayTran']=minmaxScaler.fit_transform(dayT)
<ipython-input-44-368e1a69aea5>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  BankNum['durationTran']=minmaxScaler.fit_transform(durationT)


In [47]:
BankNum.tail(30)

age  day  duration  campaign  pdays  previous  assetIndex   dayTran  \
45181   46   15        74         2    118         3    0.676334  0.466667   
45182   34   15       401         2    187         5    0.370104  0.466667   
45183   70   15        78         1     96         7    0.378775  0.466667   
45184   63   16       138         1     22         5    0.431931  0.500000   
45185   60   16       200         1     92         4    2.786325  0.500000   
45186   59   16       280         1    104         2    0.432158  0.500000   
45187   32   16       411         1     -1         0    2.085437  0.500000   
45188   29   16       236         1    550         2    1.979895  0.500000   
45189   25   16       173         1     92         5    0.373100  0.500000   
45190   32   16       206         1    188         3    0.370240  0.500000   
45191   75   16       262         1    183         1    2.685096  0.500000   
45192   29   16       238         1     -1         0    0.398793  0.500000   
45193   28   16       449         2     33         4    0.371285  0.500000   
45194   59   16       162         2    187         5    0.370331  0.500000   
45195   68   16       212         1    187         6    0.416089  0.500000   
45196   25   16       330         1     -1         0    0.380318  0.500000   
45197   36   16       270         1     -1         0    2.163288  0.500000   
45198   37   16       333         2     -1         0    0.428890  0.500000   
45199   34   16      1166         3    530        12    2.155117  0.500000   
45200   38   16      1556         4     -1         0    1.946757  0.500000   
45201   53   17       226         1    184         4    0.390532  0.533333   
45202   34   17       224         1     -1         0    0.389351  0.533333   
45203   23   17       266         1     -1         0    0.369196  0.533333   
45204   73   17       300         1     40         8    0.493441  0.533333   
45205   25   17       386         2     -1         0    0.077398  0.533333   
45206   51   17       977         3     -1         0    0.401517  0.533333   
45207   71   17       456         2     -1         0    0.442554  0.533333   
45208   72   17      1127         5    184         3    0.623495  0.533333   
45209   57   17       508         4     -1         0    0.394390  0.533333   
45210   37   17       361         2    188        11    0.498933  0.533333   

       durationTran  
45181      0.015047  
45182      0.081537  
45183      0.015860  
45184      0.028060  
45185      0.040667  
45186      0.056934  
45187      0.083571  
45188      0.047987  
45189      0.035177  
45190      0.041887  
45191      0.053274  
45192      0.048394  
45193      0.091297  
45194      0.032940  
45195      0.043107  
45196      0.067100  
45197      0.054900  
45198      0.067710  
45199      0.237088  
45200      0.316389  
45201      0.045954  
45202      0.045547  
45203      0.054087  
45204      0.061000  
45205      0.078487  
45206      0.198658  
45207      0.092721  
45208      0.229158  
45209      0.103294  
45210      0.073404

In [50]:
BankNumT=BankNum[['ageTran','dayTran','durationTran','campaign','pdays','previous','assetIndex']]

In [51]:
X=pd.concat([BankCat,BankNumT],axis=1)

In [52]:
Y=BankData['y']

In [54]:
train_x,test_x,train_y,test_y=train_test_split(X,Y,test_size=0.3,random_state=123)

In [57]:
from sklearn.linear_model import LogisticRegression

In [59]:
BankModel=LogisticRegression()

In [60]:
BankModel.fit(train_x,train_y)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [61]:
pred=BankModel.predict(test_x)

In [62]:
pred

array(['no', 'no', 'no', ..., 'no', 'no', 'no'], dtype=object)

In [63]:
from sklearn.metrics import f1_score

In [64]:
f1_score(test_y,pred,average=None,labels=['yes','no'])

array([0.30981888, 0.94214942])

In [66]:
from sklearn.preprocessing import RobustScaler
rob_scaler=RobustScaler()

In [67]:
filename="https://raw.githubusercontent.com/PacktWorkshops/The-Data-Science-Workshop/master/Chapter03/bank-full.csv"
bankdata=pd.read_csv(filename,sep=";")

In [69]:
bankdata['ageScaled']=rob_scaler.fit_transform(bankdata['age'].values.reshape(-1,1))

In [83]:
bankdata['balScaled']=rob_scaler.fit_transform(bankdata[['balance']].values.reshape(-1,1))
bankdata['durScaled']=rob_scaler.fit_transform(bankdata[['duration']].values.reshape(-1,1))






KeyError: "None of [Index(['balance'], dtype='object')] are in the [columns]"

In [84]:
bankdata.drop('balscaled',axis=1,inplace=True)

In [86]:
bankdata.dtypes

job           object
marital       object
education     object
default       object
housing       object
loan          object
contact       object
day            int64
month         object
campaign       int64
pdays          int64
previous       int64
poutcome      object
y             object
ageScaled    float64
balScaled    float64
durScaled    float64
dtype: object

In [89]:
bankCat=pd.get_dummies(bankdata[['job','marital','education','default','housing','loan','contact','month','poutcome']])

In [91]:
bankNum=bankdata[['ageScaled','balScaled','durScaled','day','campaign','pdays','previous']]

In [92]:
X=pd.concat([bankCat,bankNum],axis=1)

In [93]:
Y=bankdata['y']

In [94]:
train_x,test_x,train_y,test_y=train_test_split(X,Y,test_size=0.3,random_state=123)

In [95]:
bankML=LogisticRegression()

In [96]:
bankML.fit(train_x,train_y)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [98]:
pred=bankML.predict(test_x)

In [102]:
f1_score(test_y,pred,average=None,labels=['yes','no'])

array([0.40737564, 0.9442652 ])

In [105]:
trainData=pd.concat([train_x,train_y],axis=1)

In [106]:
ind=trainData[trainData['y']=='yes'].index

In [107]:
minData=trainData.loc[ind]

In [109]:
minData.shape

(3723, 52)

In [110]:
ind1=trainData[trainData['y']=='no'].index

In [111]:
majData=trainData.loc[ind1]

In [112]:
majSample=majData.sample(n=len(ind),random_state=123)

In [119]:
balData=pd.concat([minData,majSample],axis=0)

In [114]:
from sklearn.utils import shuffle

In [120]:
balData=shuffle(balData)

In [122]:
balData.shape

(7446, 52)

In [123]:
trainNew_x=balData.iloc[:,0:51]

In [124]:
trainNew_y=balData['y']

In [125]:
bankMLnew=LogisticRegression()
bankMLnew.fit(trainNew_x,trainNew_y)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [126]:
pred=bankMLnew.predict(test_x)

In [127]:
f1_score(test_y,pred,average=None,labels=['yes','no'])

array([0.52754454, 0.8962913 ])